In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("cognifyz Dataset .csv")

In [3]:
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [4]:
df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [6]:
df = df.drop(columns=["Address", "Locality Verbose","Locality","Longitude","Latitude","Currency","Restaurant ID",
                      "Restaurant Name","Rating color","Rating text"])

In [7]:
df

,Country Code,City,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Votes
0,162,Makati City,"French, Japanese, Desserts",1100,Yes,No,No,No,3,4.8,314
1,162,Makati City,Japanese,1200,Yes,No,No,No,3,4.5,591
2,162,Mandaluyong City,"Seafood, Asian, Filipino, Indian",4000,Yes,No,No,No,4,4.4,270
3,162,Mandaluyong City,"Japanese, Sushi",1500,No,No,No,No,4,4.9,365
4,162,Mandaluyong City,"Japanese, Korean",1500,Yes,No,No,No,4,4.8,229
...,...,...,...,...,...,...,...,...,...,...,...
9546,208,��stanbul,Turkish,80,No,No,No,No,3,4.1,788
9547,208,��stanbul,"World Cuisine, Patisserie, Cafe",105,No,No,No,No,3,4.2,1034
9548,208,��stanbul,"Italian, World Cuisine",170,No,No,No,No,4,3.7,661
9549,208,��stanbul,Restaurant Cafe,120,No,No,No,No,4,4.0,901
9550,208,��stanbul,Cafe,55,No,No,No,No,2,4.0,591

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Country Code          9551 non-null   int64
 1   City                  9551 non-null   object
 2   Cuisines              9542 non-null   object
 3   Average Cost for two  9551 non-null   int64
 4   Has Table booking     9551 non-null   object
 5   Has Online delivery   9551 non-null   object
 6   Is delivering now     9551 non-null   object
 7   Switch to order menu  9551 non-null   object
 8   Price range           9551 non-null   int64
 9   Aggregate rating      9551 non-null   float64
 10  Votes                 9551 non-null   int64
dtypes: float64(1), int64(4), object(6)
memory usage: 820.9+ KB

In [9]:
df["Has Table booking"]=df["Has Table booking"].map({"Yes": 1, "No": 0})
df["Has Online delivery"]=df["Has Online delivery"].map({"Yes": 1, "No": 0})
df["Is delivering now"]=df["Is delivering now"].map({"Yes": 1, "No": 0})
df["Switch to order menu"]=df["Switch to order menu"].map({"Yes": 1, "No": 0})

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Country Code          9551 non-null   int64
 1   City                  9551 non-null   object
 2   Cuisines              9542 non-null   object
 3   Average Cost for two  9551 non-null   int64
 4   Has Table booking     9551 non-null   int64
 5   Has Online delivery   9551 non-null   int64
 6   Is delivering now     9551 non-null   int64
 7   Switch to order menu  9551 non-null   int64
 8   Price range           9551 non-null   int64
 9   Aggregate rating      9551 non-null   float64
 10  Votes                 9551 non-null   int64
dtypes: float64(1), int64(8), object(2)
memory usage: 820.9+ KB

In [11]:
df.City.unique()

array(['Makati City', 'Mandaluyong City', 'Pasay City', 'Pasig City',
       'Quezon City', 'San Juan City', 'Santa Rosa', 'Tagaytay City',
       'Taguig City', 'Bras�_lia', 'Rio de Janeiro', 'S��o Paulo',
       'Albany', 'Armidale', 'Athens', 'Augusta', 'Balingup',
       'Beechworth', 'Boise', 'Cedar Rapids/Iowa City', 'Chatham-Kent',
       'Clatskanie', 'Cochrane', 'Columbus', 'Consort', 'Dalton',
       'Davenport', 'Des Moines', 'Dicky Beach', 'Dubuque',
       'East Ballina', 'Fernley', 'Flaxton', 'Forrest', 'Gainesville',
       'Hepburn Springs', 'Huskisson', 'Inverloch', 'Lakes Entrance',
       'Lakeview', 'Lincoln', 'Lorn', 'Macedon', 'Macon', 'Mayfield',
       'Mc Millan', 'Middleton Beach', 'Miller', 'Monroe', 'Montville',
       'Ojo Caliente', 'Orlando', 'Palm Cove', 'Paynesville', 'Penola',
       'Pensacola', 'Phillip Island', 'Pocatello', 'Potrero', 'Princeton',
       'Rest of Hawaii', 'Savannah', 'Singapore', 'Sioux City',
       'Tampa Bay', 'Tanunda', 'Trentham East', 'Valdosta', 'Vernonia',
       'Victor Harbor', 'Vineland Station', 'Waterloo', 'Weirton',
       'Winchester Bay', 'Yorkton', 'Abu Dhabi', 'Dubai', 'Sharjah',
       'Agra', 'Ahmedabad', 'Allahabad', 'Amritsar', 'Aurangabad',
       'Bangalore', 'Bhopal', 'Bhubaneshwar', 'Chandigarh', 'Chennai',
       'Coimbatore', 'Dehradun', 'Faridabad', 'Ghaziabad', 'Goa',
       'Gurgaon', 'Guwahati', 'Hyderabad', 'Indore', 'Jaipur', 'Kanpur',
       'Kochi', 'Kolkata', 'Lucknow', 'Ludhiana', 'Mangalore', 'Mohali',
       'Mumbai', 'Mysore', 'Nagpur', 'Nashik', 'New Delhi', 'Noida',
       'Panchkula', 'Patna', 'Puducherry', 'Pune', 'Ranchi',
       'Secunderabad', 'Surat', 'Vadodara', 'Varanasi', 'Vizag',
       'Bandung', 'Bogor', 'Jakarta', 'Tangerang', 'Auckland',
       'Wellington City', 'Birmingham', 'Edinburgh', 'London',
       'Manchester', 'Doha', 'Cape Town', 'Inner City', 'Johannesburg',
       'Pretoria', 'Randburg', 'Sandton', 'Colombo', 'Ankara',
       '��stanbul'], dtype=object)

In [12]:
df['City_freq'] = df['City'].map(df['City'].value_counts())

In [13]:
df

,Country Code,City,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Votes,City_freq
0,162,Makati City,"French, Japanese, Desserts",1100,1,0,0,0,3,4.8,314,2
1,162,Makati City,Japanese,1200,1,0,0,0,3,4.5,591,2
2,162,Mandaluyong City,"Seafood, Asian, Filipino, Indian",4000,1,0,0,0,4,4.4,270,4
3,162,Mandaluyong City,"Japanese, Sushi",1500,0,0,0,0,4,4.9,365,4
4,162,Mandaluyong City,"Japanese, Korean",1500,1,0,0,0,4,4.8,229,4
...,...,...,...,...,...,...,...,...,...,...,...,...
9546,208,��stanbul,Turkish,80,0,0,0,0,3,4.1,788,14
9547,208,��stanbul,"World Cuisine, Patisserie, Cafe",105,0,0,0,0,3,4.2,1034,14
9548,208,��stanbul,"Italian, World Cuisine",170,0,0,0,0,4,3.7,661,14
9549,208,��stanbul,Restaurant Cafe,120,0,0,0,0,4,4.0,901,14
9550,208,��stanbul,Cafe,55,0,0,0,0,2,4.0,591,14

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Country Code          9551 non-null   int64
 1   City                  9551 non-null   object
 2   Cuisines              9542 non-null   object
 3   Average Cost for two  9551 non-null   int64
 4   Has Table booking     9551 non-null   int64
 5   Has Online delivery   9551 non-null   int64
 6   Is delivering now     9551 non-null   int64
 7   Switch to order menu  9551 non-null   int64
 8   Price range           9551 non-null   int64
 9   Aggregate rating      9551 non-null   float64
 10  Votes                 9551 non-null   int64
 11  City_freq             9551 non-null   int64
dtypes: float64(1), int64(9), object(2)
memory usage: 895.5+ KB

In [15]:
df=df.drop(columns=["City"])

In [16]:
# Example mapping dictionary
cuisine_map = {
    'North Indian': 'Indian',
    'South Indian': 'Indian',
    'Mughlai': 'Indian',
    'Chinese': 'Asian',
    'Thai': 'Asian',
    'Japanese': 'Asian',
    'Italian': 'European',
    'French': 'European',
    'Mexican': 'Latin American',
    'American': 'Western',
    'Continental': 'Western'
}

# Apply mapping
# Apply mapping to the correct column
df['Cuisine_grouped'] = df['Cuisines'].map(cuisine_map).fillna('Other')

# Encode grouped target
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Cuisine_encoded'] = le.fit_transform(df['Cuisine_grouped'])

In [17]:
df

,Country Code,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Votes,City_freq,Cuisine_grouped,Cuisine_encoded
0,162,"French, Japanese, Desserts",1100,1,0,0,0,3,4.8,314,2,Other,4
1,162,Japanese,1200,1,0,0,0,3,4.5,591,2,Asian,0
2,162,"Seafood, Asian, Filipino, Indian",4000,1,0,0,0,4,4.4,270,4,Other,4
3,162,"Japanese, Sushi",1500,0,0,0,0,4,4.9,365,4,Other,4
4,162,"Japanese, Korean",1500,1,0,0,0,4,4.8,229,4,Other,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,208,Turkish,80,0,0,0,0,3,4.1,788,14,Other,4
9547,208,"World Cuisine, Patisserie, Cafe",105,0,0,0,0,3,4.2,1034,14,Other,4
9548,208,"Italian, World Cuisine",170,0,0,0,0,4,3.7,661,14,Other,4
9549,208,Restaurant Cafe,120,0,0,0,0,4,4.0,901,14,Other,4
9550,208,Cafe,55,0,0,0,0,2,4.0,591,14,Other,4

In [18]:
df=df.drop(columns=["Cuisines","Cuisine_grouped"])

In [19]:
df

,Country Code,Average Cost for two,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Votes,City_freq,Cuisine_encoded
0,162,1100,1,0,0,0,3,4.8,314,2,4
1,162,1200,1,0,0,0,3,4.5,591,2,0
2,162,4000,1,0,0,0,4,4.4,270,4,4
3,162,1500,0,0,0,0,4,4.9,365,4,4
4,162,1500,1,0,0,0,4,4.8,229,4,4
...,...,...,...,...,...,...,...,...,...,...,...
9546,208,80,0,0,0,0,3,4.1,788,14,4
9547,208,105,0,0,0,0,3,4.2,1034,14,4
9548,208,170,0,0,0,0,4,3.7,661,14,4
9549,208,120,0,0,0,0,4,4.0,901,14,4
9550,208,55,0,0,0,0,2,4.0,591,14,4

In [26]:
x=df.drop(columns=["Cuisine_encoded"])
y=df["Cuisine_encoded"]

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [28]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

C:\Users\dhivy\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [29]:
y_pred=lr.predict(x_test)
y_pred

array([4, 4, 4, ..., 4, 4, 4])

In [30]:
y_test

4731    2
1468    4
9037    4
7866    4
5570    4
       ..
51      4
4220    4
5165    4
8576    4
469     4
Name: Cuisine_encoded, Length: 2866, dtype: int64

In [31]:
from sklearn.metrics import accuracy_score
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8241451500348919

C:\Users\dhivy\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(